version: '3.8'

services:
  mistralrs-cpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mistralrs-cpu
    ports:
      - "1234:80"
    volumes:
      - mistralrs-data:/data
      - ./test-multi-config.json:/app/config.json
    environment:
      - HUGGINGFACE_HUB_CACHE=/data
      - PORT=80
    restart: unless-stopped
    profiles:
      - cpu

  mistralrs-gpu:
    build:
      context: .
      dockerfile: Dockerfile.cuda-all
      args:
        - CUDA_COMPUTE_CAP=89
        - WITH_FEATURES=cuda,cudnn,flash-attn
    container_name: mistralrs-gpu
    ports:
      - "1234:80"
    volumes:
      - mistralrs-data:/data
      - ./test-multi-config.json:/app/config.json
    environment:
      - HUGGINGFACE_HUB_CACHE=/data
      - PORT=80
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu

volumes:
  mistralrs-data:
    driver: local

networks:
  default:
    name: mistralrs-network