name: Docker Compose CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  docker-compose-test:
    name: Test Docker Compose Setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create .env file
      run: |
        if [ -f .env.example ]; then
          cp .env.example .env
        else
          touch .env
        fi
        echo "GITHUB_REPOSITORY=${{ github.repository }}" >> .env
        echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> .env

    - name: Test Docker Compose CPU profile
      run: |
        # Validate CPU profile compose file
        docker compose --profile cpu config > /dev/null 2>&1

        echo "✅ Docker Compose CPU profile validated"

    - name: Test Docker Compose GPU profile (build only)
      run: |
        # Note: GitHub Actions doesn't have GPU support, so we only test configuration
        docker compose --profile gpu config > /dev/null 2>&1
        echo "✅ Docker Compose GPU profile validated"

    - name: Validate Docker Compose configuration
      run: |
        # Check Docker Compose version
        docker compose version

        # Validate main config (will be minimal without profiles)
        docker compose config > /dev/null 2>&1 || true

        # Validate each profile
        docker compose --profile cpu config > /dev/null 2>&1 && echo "✅ CPU profile valid"
        docker compose --profile gpu config > /dev/null 2>&1 && echo "✅ GPU profile valid"
        docker compose --profile dev config > /dev/null 2>&1 && echo "✅ Dev profile valid"

    - name: Test development profile configuration
      run: |
        # Validate dev compose configuration
        docker compose --profile dev config > /dev/null 2>&1
        echo "✅ Development profile validated"

  docker-compose-lint:
    name: Lint Docker Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Hadolint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        ignore: DL3008,DL3009

    - name: Hadolint Dockerfile.cuda-all
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile.cuda-all
        ignore: DL3008,DL3009

    - name: Validate docker-compose.yml
      run: |
        docker compose -f docker-compose.yml config --quiet

    - name: Check for security issues with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: '.'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'