name: Docker Compose CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  docker-compose-test:
    name: Test Docker Compose Setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create .env file
      run: |
        if [ -f .env.example ]; then
          cp .env.example .env
        else
          touch .env
        fi
        echo "GITHUB_REPOSITORY=${{ github.repository }}" >> .env
        echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> .env

    - name: Test Docker Compose CPU profile
      run: |
        # Validate compose file first
        docker compose config --quiet || exit 1

        # Build image (without starting services)
        docker compose --profile cpu build --progress plain

        echo "Docker Compose CPU profile build successful"

    - name: Test Docker Compose GPU profile (build only)
      run: |
        # Note: GitHub Actions doesn't have GPU support, so we only test the build
        echo "Skipping GPU runtime test (no NVIDIA runtime in GitHub Actions)"
        # Validate GPU compose configuration
        docker compose --profile gpu config --quiet || exit 1

    - name: Validate Docker Compose configuration
      run: |
        docker compose config --quiet
        docker compose --profile cpu config --quiet
        docker compose --profile gpu config --quiet
        docker compose --profile dev config --quiet

    - name: Test development profile configuration
      run: |
        # Validate dev compose configuration
        docker compose --profile dev config --quiet || exit 1
        echo "Development profile configuration validated"

  docker-compose-lint:
    name: Lint Docker Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Hadolint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        ignore: DL3008,DL3009

    - name: Hadolint Dockerfile.cuda-all
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile.cuda-all
        ignore: DL3008,DL3009

    - name: Validate docker-compose.yml
      run: |
        docker compose -f docker-compose.yml config --quiet

    - name: Check for security issues with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: '.'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'